[workspace]
members = ["common", "service", "tap-agent"]
resolver = "2"

[workspace.package]
version = "1.0.0-alpha.0"
edition = "2021"
publish = false
license = "Apache-2.0"

[profile.dev.package."*"]
opt-level = 3
