[package]
name = "indexer-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-core = "1.0.2"
bs58 = "0.4.0"
regex = "1.7.1"
log = "0.4.17"
anyhow = "1.0.57"
reqwest = "0.11.10"
async-trait = "0.1.53"
jsonrpc-core = "18.0.0"
tokio = { version = "1", features = ["rt", "macros", "sync"] }
tracing = "0.1.34"
thiserror = "1.0.30"
futures = "0.3"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1"
actix-web = "4.2.1" 
actix-cors = "0.6.4"
env_logger = "0.9.0"
graphql-parser = "0.4.0"
# futures = { version = "0.3.1", features = ["compat"] }
lazy_static = "1.2.0"
url = "2.3.1"
diesel = { version = "1.4.8", features = ["postgres", "serde_json", "numeric", "r2d2"] }
actix-ratelimit = "0.3.1"

