[package]
name = "service"
version = "0.1.0"
edition = "2021"
description="Could not find crate on crates.io and could not import with git and path at the same time, so copied a version directly at https://github.com/graphprotocol/indexer/blob/972658b3ce8c512ad7b4dc575d29cd9d5377e3fe/packages/indexer-native/native"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-core = "2.0.0"
ethers = "2.0.0"
ethers-contract = "2.0.0"
dotenvy = "0.15"
num-bigint = "0.4.3"
bs58 = "0.4.0"
regex = "1.7.1"
log = "0.4.17"
anyhow = "1.0.57"
reqwest = "0.11.10"
async-trait = "0.1.53"
jsonrpc-core = "18.0.0"
tokio = { version = "1", features = ["rt", "macros", "sync"] }
tracing = "0.1.34"
thiserror = "1.0.30"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
actix-web = "4.2.1" 
actix-cors = "0.6.4"
env_logger = "0.9.0"
toml = "0.7.4"
graphql-parser = "0.4.0"
lazy_static = "1.2.0"
url = "2.3.1"
diesel = { version = "2.0", features = ["postgres", "serde_json", "numeric", "r2d2", "chrono"] }
diesel_derives = "2.0"
chrono = { version = "0.4", features = ["serde"] }
actix-ratelimit = "0.3.1"
async-graphql = "4.0.16"
bigdecimal = "0.3.0"
tiny-keccak = "2.0"
eip-712-derive = { git = "https://github.com/graphprotocol/eip-712-derive" }
keccak-hash = "0.10.0"
libsecp256k1 = "0.7.0"
sha3 = "0.10.6"
secp256k1 = { version = "0.20", features = ["recovery"] }
native = {path = "../native"}

[[bin]]
name = "indexer-native"
path = "native"
